Repository CS2103-AY1819S2-T12-3/main, pull requests merged in 2019-04, with the labels that each got.

#151 Restructured UG
  docs/UserGuide.adoc
Labels: v1.3

#148 Add new sort command for BatchTable
  src/main/java/seedu/address/commons/core/InformationPanelSettings.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/InventoryParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/medicine/Batch.java
  src/main/java/seedu/address/model/medicine/BatchNumber.java
  src/main/java/seedu/address/model/medicine/Expiry.java
  src/main/java/seedu/address/model/medicine/Medicine.java
  src/main/java/seedu/address/model/medicine/Quantity.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedBatch.java
  src/main/java/seedu/address/storage/JsonAdaptedMedicine.java
  src/main/java/seedu/address/ui/BatchTable.java
  src/main/java/seedu/address/ui/InformationPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MedicineCard.java
  src/main/java/seedu/address/ui/WarningCard.java
  src/main/resources/view/BatchTable.fxml
  src/main/resources/view/DarkTheme.css
  src/test/java/guitests/guihandles/MedicineCardHandle.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/UpdateBatchDescriptorTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/model/medicine/BatchTest.java
  src/test/java/seedu/address/model/medicine/MedicineTest.java
  src/test/java/seedu/address/model/medicine/QuantityTest.java
  src/test/java/seedu/address/storage/JsonAdaptedMedicineTest.java
  src/test/java/seedu/address/testutil/BatchBuilder.java
  src/test/java/seedu/address/testutil/MedicineBuilder.java
  src/test/java/seedu/address/testutil/TypicalMedicines.java
  src/test/java/seedu/address/ui/InformationPanelTest.java
  src/test/java/seedu/address/ui/MedicineListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: v1.3

#150 Update documentation
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/stylesheets/gh-pages.css
  docs/team/jonathanleewh.adoc
Labels: type.Task, v1.3

#154 Documentation for V1.3
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/UserGuide_InformationPanel.png
  docs/team/jtankw3.adoc
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/model/medicine/BatchNumber.java
  src/main/resources/view/BatchTable.fxml
Labels: v1.3

#157 PPP first draft
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/flxffy.adoc
  docs/team/johndoe.adoc
Labels: v1.3

#158 Update Junit test cases for export command
  docs/team/jonathanleewh.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/csv/CsvWrapper.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
Labels: type.Enhancement, type.Task, v1.4

#178 Fix bugs from dry run testing session
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/medicine/Expiry.java
  src/main/java/seedu/address/ui/InformationPanel.java
  src/test/java/seedu/address/commons/core/InformationPanelSettingsTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/medicine/ExpiryTest.java
  src/test/java/seedu/address/ui/InformationPanelTest.java
Labels: v1.4

#180 FindCommand added
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/InformationPanelSequenceDiagram.png
  docs/images/ModelMedicineObjectDiagram.png
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/medicine/Company.java
  src/main/java/seedu/address/model/medicine/Medicine.java
  src/main/java/seedu/address/model/medicine/UniqueMedicineList.java
  src/main/java/seedu/address/model/medicine/predicates/BatchContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/medicine/predicates/CompanyContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/medicine/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/medicine/predicates/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/BatchTable.java
  src/main/java/seedu/address/ui/InformationPanel.java
  src/test/data/JsonSerializableInventoryTest/duplicateMedicineInventory.json
  src/test/data/JsonSerializableInventoryTest/typicalMedicinesInventory.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/WarningCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/InventoryParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/medicine/ExpiryTest.java
  src/test/java/seedu/address/model/medicine/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalMedicines.java
  src/test/java/seedu/address/ui/InformationPanelTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/MediTabsSystemTest.java
Labels: v1.4

#181 Update documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/jonathanleewh.adoc
Labels: type.Task, v1.4

#182 Mid 1.4
  PDF/foo.txt
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/LabelUML.png
  docs/images/UMLLabelDiagram.png
  docs/images/mainPDF.PNG
  docs/team/melpulomas.adoc
  src/main/java/seedu/address/commons/util/pdf/PdfWrapper.java
Labels: v1.4

#183 Fix bug and improve test
  src/main/java/seedu/address/model/medicine/Quantity.java
  src/test/data/JsonSerializableInventoryTest/typicalMedicinesInventory.json
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/testutil/TypicalMedicines.java
  src/test/java/seedu/address/ui/InformationPanelTest.java
Labels: v1.4

#185 Update DeveloperGuide.adoc based on review
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/jonathanleewh.adoc
Labels: type.Task, v1.4

#186 Update documentation and prepare MediTabs for v1.4 milestone
  docs/team/jonathanleewh.adoc
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, v1.4

#187 Update UserGuide.adoc
  docs/UserGuide.adoc
Labels: type.Task, v1.4

#190 Codestyle and debugging
  src/main/java/seedu/address/commons/core/InformationPanelSettings.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/medicine/Batch.java
  src/main/java/seedu/address/model/medicine/BatchNumber.java
  src/main/java/seedu/address/model/medicine/Company.java
  src/main/java/seedu/address/model/medicine/Medicine.java
  src/main/java/seedu/address/model/medicine/Name.java
  src/main/java/seedu/address/model/medicine/Quantity.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/JsonAdaptedBatch.java
  src/main/java/seedu/address/ui/BatchTable.java
  src/main/java/seedu/address/ui/InformationPanel.java
  src/main/resources/view/BatchTable.fxml
  src/test/data/JsonSerializableInventoryTest/typicalMedicinesInventory.json
  src/test/java/guitests/guihandles/InformationPanelHandle.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/commons/core/InformationPanelSettingsTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateBatchDescriptorTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/medicine/BatchNumberTest.java
  src/test/java/seedu/address/model/medicine/CompanyTest.java
  src/test/java/seedu/address/model/medicine/NameTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBatchTest.java
  src/test/java/seedu/address/testutil/TypicalMedicines.java
  src/test/java/seedu/address/ui/InformationPanelTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/MediTabsSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
  src/test/java/systemtests/UpdateCommandSystemTest.java
Labels: v1.4

#192 Improve Export Command
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/util/FileName.java
  src/main/java/seedu/address/commons/util/csv/CsvWrapper.java
Labels: type.Task, v1.4

#193 Change order of medicine card fields
  src/main/java/seedu/address/commons/core/InformationPanelSettings.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/ui/MedicineCard.java
  src/main/resources/view/MedicineListCard.fxml
  src/test/java/guitests/guihandles/StageHandle.java
Labels: v1.4

#191 Edited user, developer and Label command [1.4]
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/BlankUI.png
  docs/images/ConfirmationMessage.png
  docs/images/LabelActivityDiagram.png
  docs/images/LabelUML.png
  docs/images/MockUp.png
  docs/images/Ui.png
  docs/images/label1.png
  docs/images/label2.png
  docs/images/label2_taken.png
  docs/images/mainPDF.PNG
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/pdf/PdfWrapper.java
  src/main/java/seedu/address/logic/commands/LabelCommand.java
  src/main/java/seedu/address/logic/parser/LabelCommandParser.java
  src/test/java/seedu/address/logic/commands/LabelCommandTest.java
Labels: v1.4

#197 Improve documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/util/csv/CsvWrapper.java
Labels: type.Task, v1.4

#195 V1.4 Documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/PPP_Ui_WarningPanel.png
  docs/images/WarningCommandActivityDiagram.png
  docs/images/WarningPanelSequenceDiagram.png
  docs/team/flxffy.adoc
  src/main/java/seedu/address/commons/util/warning/WarningPanelPredicateAccessor.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/WarningCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/medicine/predicates/BatchExpiryThresholdPredicate.java
  src/main/java/seedu/address/model/medicine/predicates/MedicineExpiryThresholdPredicate.java
  src/main/java/seedu/address/model/medicine/predicates/MedicineLowStockThresholdPredicate.java
  src/main/java/seedu/address/model/threshold/Threshold.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/WarningPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/WarningPanel.fxml
  src/test/java/seedu/address/commons/util/warning/WarningPanelPredicateAccessorTest.java
  src/test/java/seedu/address/logic/parser/WarningCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/medicine/BatchExpiryThresholdPredicateTest.java
  src/test/java/seedu/address/model/medicine/MedicineExpiryThresholdPredicateTest.java
  src/test/java/seedu/address/model/medicine/MedicineLowStockThresholdPredicateTest.java
Labels: v1.4

#200 Update documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/flxffy.adoc
  docs/team/jonathanleewh.adoc
Labels: type.Task, v1.4

#199 Fix error and edit documentation for v1.4
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/BlankUI.png
  docs/images/MockUp.png
  docs/images/Ui.png
  docs/images/folderPDF.png
  docs/images/mainPDF.PNG
  docs/team/melpulomas.adoc
Labels: v1.4

#196 User and Developer Guide for V1.4
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/InformationPanelActivityDiagram.pptx
  docs/diagrams/ModelComponentClassBetterOopDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/ModelMedicineObjectDiagram.pptx
  docs/diagrams/SDforDeleteMedicine.pptx
  docs/images/InformationPanelActivityDiagram.png
  docs/images/InformationPanelSequenceDiagram.png
  docs/images/ModelClassBetterOopDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ModelMedicineObjectDiagram.png
  docs/images/SDforDeleteMedicine.png
  docs/images/Ui.png
  docs/images/UserGuide_InformationPanel.png
  docs/images/UserGuide_ListCommand.png
  docs/images/UserGuide_SelectCommand.png
  docs/team/jtankw3.adoc
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/BatchTable.java
  src/main/java/seedu/address/ui/InformationPanel.java
Labels: v1.4

#201 Fix formatting issues with documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: v1.4
