Repository CS2103-AY1819S2-T12-3/main, pull requests merged in 2019-03, with the labels that each got.

#54 Update Travis, Appveyor and Coveralls badges url
  README.adoc
Labels: priority.High

#57 Update export command support
  README.adoc
  build.gradle
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/model/medicine/Medicine.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/csv/CsvWrapper.java
Labels: v1.2

#77 [mid v1.2] Add more validation to UpdateCommand
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/model/medicine/Batch.java
  src/main/java/seedu/address/model/medicine/BatchNumber.java
  src/main/java/seedu/address/model/medicine/Expiry.java
  src/main/java/seedu/address/model/medicine/Medicine.java
  src/main/java/seedu/address/model/medicine/Quantity.java
  src/main/java/seedu/address/storage/JsonAdaptedBatch.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/model/medicine/QuantityTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Enhancement, v1.2

#79 Update developer guide
  docs/DeveloperGuide.adoc
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/commons/util/csv/CsvWrapper.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
Labels: type.Task, v1.2

#96 Update developer guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ExportCommandSequenceDiagramOverview.png
Labels: type.Task, v1.2

#102 [v1.2] Update developers guide and user guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ModelComponentClassBetterOopDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/UndoRedoActivityDiagram.pptx
  docs/diagrams/UndoRedoExecuteUndoStateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand1StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand2StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand3StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand4StateListDiagram.pptx
  docs/diagrams/UndoRedoSequenceDiagram.pptx
  docs/diagrams/UndoRedoStartingStateListDiagram.pptx
  docs/images/BatchTableSequenceDiagram.png
  docs/images/ModelClassBetterOopDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ModelMedicineObjectDiagram.png
  docs/images/UndoRedoActivityDiagram.png
  docs/images/UndoRedoExecuteUndoStateListDiagram.png
  docs/images/UndoRedoNewCommand1StateListDiagram.png
  docs/images/UndoRedoNewCommand2StateListDiagram.png
  docs/images/UndoRedoNewCommand3StateListDiagram.png
  docs/images/UndoRedoNewCommand4StateListDiagram.png
  docs/images/UndoRedoSequenceDiagram.png
  docs/images/UndoRedoStartingStateListDiagram.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LabelCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/medicine/Company.java
  src/main/java/seedu/address/model/medicine/Medicine.java
  src/main/java/seedu/address/storage/JsonAdaptedMedicine.java
  src/main/java/seedu/address/ui/BatchTable.java
  src/main/java/seedu/address/ui/InformationPanel.java
  src/main/java/seedu/address/ui/MedicineCard.java
  src/main/java/seedu/address/ui/WarningCard.java
  src/test/data/JsonInventoryStorageTest/invalidAndValidMedicineInventory.json
  src/test/data/JsonInventoryStorageTest/invalidMedicineInventory.json
  src/test/data/JsonSerializableInventoryTest/duplicateMedicineInventory.json
  src/test/data/JsonSerializableInventoryTest/invalidMedicineInventory.json
  src/test/data/JsonSerializableInventoryTest/typicalMedicinesInventory.json
  src/test/java/guitests/guihandles/MedicineCardHandle.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedMedicineTest.java
  src/test/java/seedu/address/testutil/MedicineBuilder.java
  src/test/java/seedu/address/testutil/MedicineUtil.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: v1.2

#103 Add test for JsonAdaptedBatch and JsonAdaptedMedicine
  src/test/data/JsonSerializableInventoryTest/typicalMedicinesInventory.json
  src/test/java/seedu/address/storage/JsonAdaptedBatchTest.java
  src/test/java/seedu/address/storage/JsonAdaptedMedicineTest.java
  src/test/java/seedu/address/testutil/TypicalMedicines.java
Labels: v1.2

#104 Added renaming feature to LabelCommand and updated UserGuide
  docs/UserGuide.adoc
  docs/images/Label1_example.png
  docs/images/label2_example.png
  src/main/java/seedu/address/logic/commands/LabelCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/LabelCommandParser.java
Labels: priority.High, v1.2

#107 Update Ui.png GUI image
  docs/images/Ui.png
Labels: type.Task, v1.2

#108 Update MediTabs version number to match milestone
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, v1.2

#109 V1.2 Developer Guide
  docs/DeveloperGuide.adoc
  docs/images/UiClassDiagram.png
  docs/images/WarningPanelSequenceDiagram.png
  src/main/java/seedu/address/ui/WarningPanel.java
Labels: type.Task, v1.2

#110 [V1.2] Updated user guide
  docs/UserGuide.adoc
Labels: type.Task, v1.2

#112 v1.2 Final touches to developers guide
  docs/DeveloperGuide.adoc
  docs/diagrams/LogicComponentClassDiagram.pptx
  docs/diagrams/LogicComponentSequenceDiagram.pptx
  docs/diagrams/SDforDeleteMedicine.pptx
  docs/images/LogicClassDiagram.png
  docs/images/SDforDeleteMedicine.png
  docs/images/SDforDeletePerson.png
  docs/images/UserGuide_WarningPanel.png
Labels: type.Task, v1.2

#115 Update UserGuide.adoc Export Command Description
  docs/UserGuide.adoc
  docs/images/SampleCSVFileImage.PNG
Labels: type.Task, v1.3

#116 Update UserGuide.adoc
  docs/UserGuide.adoc
  docs/images/SampleCSVFileImage.png
  docs/images/damithc.jpg
  docs/images/lejolly.jpg
  docs/images/m133225.jpg
  docs/images/yl_coder.jpg
Labels: type.Task, v1.3

#117 Update AboutUs, ContactUs, UserGuide, DevelopeGuide, FileName.java and FileNameTest.java
  docs/AboutUs.adoc
  docs/ContactUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ExportCommandActivityDiagram.png
  src/main/java/seedu/address/commons/util/FileName.java
  src/test/java/seedu/address/commons/util/FileNameTest.java
Labels: type.Enhancement, type.Task, v1.3

#121 Post warning panel v1.2 clean up
  src/main/java/seedu/address/commons/util/warning/WarningPanelListType.java
  src/main/java/seedu/address/commons/util/warning/WarningPanelPredicateAccessor.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/medicine/BatchExpiryThresholdPredicate.java
  src/main/java/seedu/address/model/medicine/Medicine.java
  src/main/java/seedu/address/model/medicine/MedicineExpiryThresholdPredicate.java
  src/main/java/seedu/address/model/medicine/MedicineLowStockThresholdPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/WarningCard.java
  src/main/java/seedu/address/ui/WarningListView.java
  src/main/java/seedu/address/ui/WarningPanel.java
  src/main/resources/view/WarningContentCell.fxml
  src/main/resources/view/WarningListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: v1.3

#122 Improve export command and add JUnit test cases
  README.adoc
  build.gradle
  src/main/java/seedu/address/commons/util/csv/CsvWrapper.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: priority.High, type.Enhancement, type.Task, v1.3

#123 Update UserGuide.adoc to match updated export command implementation
  docs/UserGuide.adoc
  docs/images/SampleCSVFileImage.png
Labels: type.Task, v1.3

#124 mid V1.3 Warning Command
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/warning/WarningPanelPredicateAccessor.java
  src/main/java/seedu/address/logic/commands/WarningCommand.java
  src/main/java/seedu/address/logic/parser/InventoryParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/WarningCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/medicine/BatchExpiryThresholdPredicate.java
  src/main/java/seedu/address/model/medicine/MedicineExpiryThresholdPredicate.java
  src/main/java/seedu/address/model/medicine/MedicineLowStockThresholdPredicate.java
  src/main/java/seedu/address/model/threshold/Threshold.java
Labels: v1.3

#131 Created Junit Test Cases for Label Command
  PDF/foo.txt
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/LabelCommand.java
  src/test/java/seedu/address/logic/commands/LabelCommandTest.java
Labels: priority.High

#128 Improvements to InformationPanel feature
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/InformationPanelSequenceDiagram.png
  docs/images/UserGuide_Components.png
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/address/model/medicine/Medicine.java
  src/main/java/seedu/address/ui/BatchTable.java
  src/main/resources/view/BatchTable.fxml
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/UpdateCommandParserTest.java
  src/test/java/seedu/address/testutil/MedicineBuilder.java
  src/test/java/seedu/address/testutil/UpdateBatchDescriptorBuilder.java
Labels: v1.3

#135 Update UserGuide.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ExportCommandActivityDiagram.png
Labels: type.Task, v1.3

#134 Update DarkTheme CSS
  docs/images/Ui.png
  docs/images/UserGuide_WarningPanel.png
  src/main/java/seedu/address/logic/commands/WarningCommand.java
  src/main/java/seedu/address/ui/WarningPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/WarningListCard.fxml
  src/main/resources/view/WarningListView.fxml
Labels: type.Enhancement, v1.3

#137 Update CsvWrapper.java to improve exported CSV file data
  docs/UserGuide.adoc
  docs/images/SampleCSVFileImage.png
  src/main/java/seedu/address/commons/util/csv/CsvWrapper.java
  src/main/java/seedu/address/model/medicine/Medicine.java
  src/test/java/seedu/address/commons/util/FileNameTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: type.Enhancement, type.Task, v1.3

#139 V1.3 Model, Logic tests
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/commons/core/WarningPanelSettings.java
  src/main/java/seedu/address/commons/util/csv/CsvWrapper.java
  src/main/java/seedu/address/commons/util/warning/WarningPanelPredicateAccessor.java
  src/main/java/seedu/address/commons/util/warning/WarningPanelPredicateType.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/WarningCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/WarningCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/medicine/BatchExpiryThresholdPredicate.java
  src/main/java/seedu/address/model/medicine/Expiry.java
  src/main/java/seedu/address/model/medicine/MedicineExpiryThresholdPredicate.java
  src/main/java/seedu/address/model/medicine/MedicineLowStockThresholdPredicate.java
  src/main/java/seedu/address/model/medicine/Quantity.java
  src/main/java/seedu/address/model/threshold/Threshold.java
  src/main/java/seedu/address/ui/WarningCard.java
  src/main/java/seedu/address/ui/WarningListView.java
  src/main/java/seedu/address/ui/WarningPanel.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/warning/WarningPanelPredicateAccessorTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/WarningCommandTest.java
  src/test/java/seedu/address/logic/parser/WarningCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/medicine/BatchExpiryThresholdPredicateTest.java
  src/test/java/seedu/address/model/medicine/MedicineExpiryThresholdPredicateTest.java
  src/test/java/seedu/address/model/medicine/MedicineLowStockThresholdPredicateTest.java
  src/test/java/seedu/address/model/threshold/ThresholdTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: v1.3

#140 Update User Guide and Developer Guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.Task, v1.3

#141 Improve UserGuide.adoc, DeveloperGuide.adoc and FileName.java
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/util/FileName.java
  src/test/java/seedu/address/commons/util/FileNameTest.java
Labels: type.Enhancement, type.Task, v1.3

#142 Created parser test and helper class for Label Command
  docs/UserGuide.adoc
  docs/images/Label1_example.png
  docs/images/label1.png
  docs/images/label2.png
  docs/images/label2_example.png
  docs/images/label2_taken.png
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/commons/util/pdf/PdfWrapper.java
  src/main/java/seedu/address/logic/commands/LabelCommand.java
  src/main/java/seedu/address/logic/parser/LabelCommandParser.java
  src/test/java/seedu/address/logic/commands/LabelCommandTest.java
  src/test/java/seedu/address/logic/parser/LabelCommandParserTest.java
Labels: v1.3
